/**
 * Utility functions for generating printable calculator results
 */

interface PrintConfig {
  calculatorName: string;
  result: any;
  inputs: Record<string, any>;
  patientId?: string | null;
  additionalInfo?: Record<string, any>;
}

/**
 * Generate a printable HTML document for calculator results
 */
export function generatePrintableHTML({
  calculatorName,
  result,
  inputs,
  patientId = null,
  additionalInfo = {}
}: PrintConfig): string {
  const currentDate = new Date().toLocaleDateString('en-US', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
    hour: '2-digit',
    minute: '2-digit'
  });

  const printStyles = `
    <style>
      @media print {
        @page {
          margin: 1.5cm;
          size: A4;
        }
      }
      
      body {
        font-family: Arial, sans-serif;
        line-height: 1.4;
        color: #333;
        max-width: 800px;
        margin: 0 auto;
        padding: 10px;
        font-size: 14px;
      }
      
      .print-header {
        text-align: center;
        border-bottom: 2px solid #0066cc;
        padding-bottom: 12px;
        margin-bottom: 15px;
      }
      
      .print-header h1 {
        color: #0066cc;
        margin: 0;
        font-size: 24px;
      }
      
      .print-header .subtitle {
        color: #666;
        margin: 3px 0;
        font-size: 14px;
      }
      
      .patient-info {
        background: #f8f9fa;
        padding: 10px;
        border-radius: 5px;
        margin-bottom: 15px;
        font-size: 13px;
      }
      
      .patient-info h3 {
        margin: 0 0 8px 0;
        color: #0066cc;
        font-size: 16px;
      }
      
      .result-section {
        margin-bottom: 15px;
        text-align: center;
      }
      
      .result-value {
        font-size: 28px;
        font-weight: bold;
        color: #0066cc;
        margin: 8px 0;
      }
      
      .result-category {
        font-size: 18px;
        font-weight: 500;
        margin: 8px 0;
      }
      
      .category-normal { color: #28a745; }
      .category-underweight { color: #17a2b8; }
      .category-overweight { color: #ffc107; }
      .category-obese { color: #dc3545; }
      
      .content-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 15px;
        margin-bottom: 15px;
      }
      
      .input-section,
      .formula-section,
      .interpretation-section {
        padding: 10px;
        border: 1px solid #ddd;
        border-radius: 5px;
        font-size: 13px;
      }
      
      .section-title {
        font-weight: bold;
        color: #0066cc;
        margin-bottom: 8px;
        font-size: 14px;
      }
      
      .input-item,
      .range-item {
        margin: 3px 0;
        display: flex;
        justify-content: space-between;
        font-size: 12px;
      }
      
      .formula-description {
        font-style: italic;
        color: #666;
        margin-top: 5px;
        font-size: 12px;
      }
      
      .print-footer {
        text-align: center;
        margin-top: 20px;
        padding-top: 15px;
        border-top: 1px solid #ddd;
        color: #666;
        font-size: 12px;
      }
      
      .ranges-grid {
        display: grid;
        grid-template-columns: 1fr 1fr;
        gap: 5px;
        margin-top: 8px;
      }
      
      .ranges-grid .range-item {
        font-size: 11px;
      }
      
      @media (max-width: 600px) {
        .content-grid {
          grid-template-columns: 1fr;
        }
        
        .ranges-grid {
          grid-template-columns: 1fr;
        }
        
        .input-item,
        .range-item {
          flex-direction: column;
        }
      }
    </style>
  `;

  const patientSection = patientId ? `
    <div class="patient-info">
      <h3>Patient Information</h3>
      <div><strong>Patient ID:</strong> ${escapeHtml(patientId)}</div>
    </div>
  ` : '';

  return `
    <!DOCTYPE html>
    <html lang="en">
    <head>
      <meta charset="UTF-8">
      <meta name="viewport" content="width=device-width, initial-scale=1.0">
      <title>${calculatorName} Report${patientId ? ' - ' + escapeHtml(patientId) : ''}</title>
      ${printStyles}
    </head>
    <body>
      <div class="print-header">
        <h1>MediCal ${calculatorName}</h1>
        <div class="subtitle">Medical Calculator Report</div>
      </div>
      
      ${patientSection}
      
      ${generateResultSection(result, calculatorName)}
      
      <div class="content-grid">
        <div class="left-column">
          ${generateInputSection(inputs)}
          ${generateAdditionalInfoSection(additionalInfo)}
        </div>
        <div class="right-column">
          ${generateFormulaSection(result.formula)}
          ${generateInterpretationSection(result.interpretation)}
        </div>
      </div>
      
      <div class="print-footer">
        <div>Generated by MediCal - Medical Calculator Tools</div>
        <div>Report generated on ${currentDate}</div>
        <div>&copy; 2025 CCDRD AG</div>
      </div>
    </body>
    </html>
  `;
}

/**
 * Generate the result section HTML
 */
function generateResultSection(result: any, calculatorName: string): string {
  const categoryClass = `category-${result.category.toLowerCase().replace(/\s+/g, '-')}`;
  
  let resultLabel = 'Result';
  let resultValue = result.bmi;
  let resultUnit = '';
  
  // Handle different result types
  if (result.formula && result.formula.name) {
    if (result.formula.name.includes('BMI Prime')) {
      resultLabel = 'BMI Prime';
    } else if (result.formula.name.includes('Reciprocal') || result.formula.name.includes('Ponderal')) {
      resultLabel = 'Ponderal Index';
    } else {
      resultLabel = 'BMI';
      resultUnit = ' kg/m²';
    }
  }
  
  return `
    <div class="result-section">
      <div class="section-title">${calculatorName} Results</div>
      <div class="result-value">${resultLabel}: ${resultValue}${resultUnit}</div>
      <div class="result-category ${categoryClass}">Category: ${result.category}</div>
    </div>
  `;
}

/**
 * Generate the input section HTML
 */
function generateInputSection(inputs: Record<string, any>): string {
  const inputItems = Object.entries(inputs)
    .map(([key, value]) => {
      const label = formatInputLabel(key);
      const formattedValue = formatInputValue(key, value);
      return `<div class="input-item"><span>${label}:</span><span>${formattedValue}</span></div>`;
    })
    .join('');

  return `
    <div class="input-section">
      <div class="section-title">Input Values</div>
      ${inputItems}
    </div>
  `;
}

/**
 * Generate the formula section HTML
 */
function generateFormulaSection(formula: any): string {
  if (!formula) return '';
  
  return `
    <div class="formula-section">
      <div class="section-title">Formula Information</div>
      <div><strong>Formula:</strong> ${formula.name}</div>
      <div class="formula-description">${formula.description}</div>
    </div>
  `;
}

/**
 * Generate the interpretation section HTML
 */
function generateInterpretationSection(interpretation: any): string {
  if (!interpretation || !interpretation.ranges) return '';
  
  const rangeItems = Object.entries(interpretation.ranges)
    .map(([category, range]) => {
      const categoryLabel = category.charAt(0).toUpperCase() + category.slice(1);
      return `<div class="range-item"><span>${categoryLabel}:</span><span>${range}</span></div>`;
    })
    .join('');

  return `
    <div class="interpretation-section">
      <div class="section-title">Category Ranges</div>
      <div class="ranges-grid">
        ${rangeItems}
      </div>
    </div>
  `;
}

/**
 * Generate additional information section HTML
 */
function generateAdditionalInfoSection(additionalInfo: Record<string, any>): string {
  if (!additionalInfo || Object.keys(additionalInfo).length === 0) return '';
  
  const infoItems = Object.entries(additionalInfo)
    .filter(([key, value]) => value !== undefined && value !== null && value !== '')
    .map(([key, value]) => {
      const label = formatInputLabel(key);
      return `<div class="input-item"><span>${label}:</span><span>${value}</span></div>`;
    })
    .join('');

  if (!infoItems) return '';

  return `
    <div class="input-section">
      <div class="section-title">Additional Information</div>
      ${infoItems}
    </div>
  `;
}

/**
 * Format input labels for display
 */
function formatInputLabel(key: string): string {
  const labelMap: Record<string, string> = {
    weight: 'Weight',
    height: 'Height',
    heightMeters: 'Height (meters)',
    formula: 'Formula Used',
    unit: 'Unit System',
    calculationDate: 'Calculation Date',
    formulaUsed: 'Formula Used'
  };
  
  return labelMap[key] || key.charAt(0).toUpperCase() + key.slice(1).replace(/([A-Z])/g, ' $1');
}

/**
 * Format input values for display
 */
function formatInputValue(key: string, value: any): string {
  const unitMap: Record<string, string> = {
    weight: ' kg',
    height: ' cm',
    heightMeters: ' m'
  };
  
  if (typeof value === 'number') {
    return value + (unitMap[key] || '');
  }
  
  return String(value);
}

/**
 * Escape HTML characters to prevent XSS
 */
function escapeHtml(text: string): string {
  if (typeof document !== 'undefined') {
    const div = document.createElement('div');
    div.textContent = text;
    return div.innerHTML;
  }
  
  // Fallback for server-side rendering
  return text
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;');
}

/**
 * Open the print dialog with the generated HTML
 */
export function openPrintDialog(htmlContent: string): void {
  const printWindow = window.open('', '_blank');
  
  if (!printWindow) {
    alert('Please allow popups to enable printing functionality.');
    return;
  }
  
  printWindow.document.write(htmlContent);
  printWindow.document.close();
  
  // Wait for content to load, then print
  printWindow.onload = () => {
    printWindow.focus();
    printWindow.print();
    
    // Close the window after printing (optional)
    printWindow.onafterprint = () => {
      printWindow.close();
    };
  };
}